// -- 0xrex Website -- Shared JavaScript --

// Mobile nav toggle
document.addEventListener('DOMContentLoaded', () => {
  const toggle = document.getElementById('navToggle');
  const links = document.getElementById('navLinks');
  if (toggle && links) {
    toggle.addEventListener('click', () => {
      links.classList.toggle('open');
    });
  }

  // Scroll animations (intersection observer)
  const animateEls = document.querySelectorAll('.animate-in');
  if (animateEls.length && 'IntersectionObserver' in window) {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.style.animationPlayState = 'running';
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.1 });

    animateEls.forEach(el => {
      el.style.animationPlayState = 'paused';
      observer.observe(el);
    });
  }
});

// -- Hero Tag Typing + Glitch Swap Animation --
document.addEventListener('DOMContentLoaded', () => {
  const el = document.getElementById('heroTagTyping');
  const cursor = document.querySelector('.tag-cursor');
  if (!el) return;
  const lines = [
    'AGENT ONLINE -- AUTONOMOUS TRADING ACTIVATED',
    'SCANNING 1,000+ CRYPTO ASSETS...',
    'SIGNAL ENGINE ARMED -- 9 EXCHANGES CONNECTED',
    'CRYPTOCRED TA + GCR RULESET ENGAGED',
    'RISK MATRIX NOMINAL -- CIRCUIT BREAKERS SET',
    'SL/TP MONITOR ACTIVE -- 30s INTERVAL',
  ];
  const glitchChars = '!@#$%&*_+=<>?/\\|';
  let lineIdx = 0;

  let i = 0;
  function typeFirst() {
    el.textContent = lines[0].slice(0, i + 1);
    i++;
    if (i < lines[0].length) {
      setTimeout(typeFirst, 40);
    } else {
      if (cursor) cursor.style.animation = 'blink-cursor 0.7s step-end infinite';
      setTimeout(nextLine, 3000);
    }
  }

  function glitchSwap(newText) {
    const len = newText.length;
    let step = 0;
    const totalSteps = 6;
    function frame() {
      if (step < totalSteps) {
        let out = '';
        for (let c = 0; c < len; c++) {
          out += Math.random() < 0.6
            ? glitchChars[Math.floor(Math.random() * glitchChars.length)]
            : newText[c];
        }
        el.textContent = out;
        el.style.opacity = Math.random() < 0.3 ? '0.4' : '1';
        step++;
        setTimeout(frame, 50);
      } else {
        el.textContent = newText;
        el.style.opacity = '1';
        setTimeout(nextLine, 4000);
      }
    }
    frame();
  }

  function nextLine() {
    lineIdx = (lineIdx + 1) % lines.length;
    glitchSwap(lines[lineIdx]);
  }

  typeFirst();
});

// -- Legal Modal --
const _LEGAL_CONTENT = {
  privacy: {
    title: 'PRIVACY POLICY',
    html: `
      <h2>Information We Collect</h2>
      <p>0xrex operates entirely on your local machine. We do not collect, store, or transmit any personal data to external servers. All trading data, portfolio information, and configuration settings remain on your device.</p>
      <h2>Exchange API Credentials</h2>
      <p>API keys and secrets you provide for exchange connections are stored locally on your device using encryption. They are never transmitted to 0xrex servers or any third party. Credentials are used solely to communicate directly between your device and your chosen exchange.</p>
      <h2>Market Data</h2>
      <p>Market data is fetched from public APIs directly from your device. These services may log your IP address per their own privacy policies.</p>
      <h2>Analytics & Telemetry</h2>
      <p>0xrex does not include any analytics, telemetry, tracking pixels, or third-party scripts. No usage data leaves your machine.</p>
      <h2>Data Retention</h2>
      <p>All data is stored in local databases and JSON files within the application directory. You can delete all data at any time by removing the data folder.</p>
    `
  },
  terms: {
    title: 'TERMS & CONDITIONS',
    html: `
      <h2>Acceptance of Terms</h2>
      <p>By using 0xrex ("the Software"), you agree to these terms. If you do not agree, do not use the Software.</p>
      <h2>Nature of the Software</h2>
      <p>0xrex is an experimental trading analysis and automation tool. It is provided for educational and research purposes only. It is not a registered financial advisor, broker-dealer, or investment service.</p>
      <h2>No Financial Advice</h2>
      <p>Nothing in this Software constitutes financial, investment, tax, or legal advice. All signals, recommendations, and analysis generated by 0xrex are algorithmic outputs and should not be treated as professional advice.</p>
      <h2>Risk Disclosure</h2>
      <ul>
        <li>Trading cryptocurrencies involves substantial risk of loss.</li>
        <li>Past performance of any algorithm does not guarantee future results.</li>
        <li>You may lose some or all of your invested capital.</li>
        <li>Automated trading systems can malfunction, execute unintended trades, or fail to execute intended trades.</li>
        <li>Cryptocurrency markets operate 24/7 and can be extremely volatile.</li>
      </ul>
      <h2>Limitation of Liability</h2>
      <p>The authors and contributors of 0xrex are not liable for any financial losses, damages, or other consequences arising from the use of this Software. You use 0xrex entirely at your own risk.</p>
      <h2>No Warranty</h2>
      <p>The Software is provided "AS IS" without warranty of any kind.</p>
    `
  },
  transparency: {
    title: 'TRANSPARENCY REPORT',
    html: `
      <h2>How 0xrex Works</h2>
      <p>0xrex is an autonomous crypto trading agent that analyses market conditions and generates trade signals using a combination of technical indicators, market regime classification, and risk-adjusted position sizing.</p>
      <h2>Signal Generation</h2>
      <p>Trade signals are generated using:</p>
      <ul>
        <li><strong>RSI (Relative Strength Index)</strong> -- momentum and overbought/oversold conditions.</li>
        <li><strong>MACD</strong> -- trend direction and crossover signals.</li>
        <li><strong>Bollinger Bands</strong> -- volatility and mean reversion detection.</li>
        <li><strong>ATR</strong> -- average true range for stop-loss/take-profit placement.</li>
        <li><strong>Market regime classification</strong> -- Bull, Bear, Accumulation, Distribution, Ranging.</li>
        <li><strong>Confidence scoring</strong> -- composite score with minimum threshold filtering (default 60%).</li>
      </ul>
      <h2>Trading Methodology</h2>
      <ul>
        <li><strong>CryptoCred TA</strong> -- technical analysis principles for crypto-specific market structure.</li>
        <li><strong>GCR Contrarian</strong> -- contrarian investing rules: fade extreme sentiment, buy boredom, sell euphoria.</li>
      </ul>
      <h2>Limitations</h2>
      <ul>
        <li>Price data may have slight delays depending on the data source.</li>
        <li>Signal confidence scores are statistical estimates, not certainties.</li>
        <li>The system does not account for all market risks (liquidity, regulatory, smart contract).</li>
      </ul>
    `
  }
};

function openLegalModal(type) {
  const content = _LEGAL_CONTENT[type];
  if (!content) return;
  document.getElementById('legalModalTitle').textContent = content.title;
  document.getElementById('legalModalBody').innerHTML = content.html;
  document.getElementById('legalModalOverlay').classList.remove('hidden');
}

function closeLegalModal() {
  document.getElementById('legalModalOverlay').classList.add('hidden');
}

// -- Demo Radar Telemetry --
document.addEventListener('DOMContentLoaded', () => {
  const telem = document.getElementById('demoRadarTelem');
  if (!telem) return;

  const lines = [
    'SYS.INIT 0x4F2A OK', 'WS.LINK CONNECTED',
    'SCAN CRYPTO — 1,000+ ASSETS', 'RSI CALC BTC 34.2',
    'SIG BUY ETH 0.82', 'RISK CHK NOMINAL',
    'RGM BULL DETECTED', 'NET.PING 8ms',
    'ORD FILL 0.5 BTC @ 67432', 'CIRC.BRK ARMED',
    'SCAN FULL UNIVERSE 108', 'HASH 0xA3F1 VERIFIED',
    'SIG SELL DOGE 0.71', 'VaR -1.8% OK',
    'CORR BTC/ETH 0.87', 'SENT BEARISH -0.12',
    'ALLOC REBAL 8 POS', 'LOOP CYCLE 42 DONE',
    'SOL $142.8 +3.2%', 'ARB $1.24 +1.8%',
  ];
  let idx = 0;

  function addTelem() {
    const div = document.createElement('div');
    const cls = Math.random() < 0.15 ? ' tl-red' : Math.random() < 0.3 ? ' tl-green' : '';
    div.className = 'demo-telem-line' + cls;
    div.textContent = '> ' + lines[idx % lines.length];
    telem.appendChild(div);
    if (telem.children.length > 12) telem.removeChild(telem.firstChild);
    idx++;
    setTimeout(addTelem, 800 + Math.random() * 1500);
  }
  addTelem();
});

// -- Demo Ops Log --
document.addEventListener('DOMContentLoaded', () => {
  const log = document.getElementById('demoOpsLog');
  if (!log) return;

  const entries = [
    { cmd: 'SYS.BOOT', msg: '0xrex agent initialising...' },
    { cmd: 'WS.LINK', msg: 'WebSocket connected to Binance' },
    { cmd: 'MKT.SCAN', msg: 'Loading 1,000+ crypto assets...' },
    { cmd: 'RGM.CALC', msg: 'Regime: BULL TREND -- momentum rising' },
    { cmd: 'SIG.GEN', msg: 'BTC/USDT -- BUY signal -- confidence 0.82' },
    { cmd: 'SIG.GEN', msg: 'DOGE/USDT -- HOLD -- confidence 0.48', cls: 'warn' },
    { cmd: 'RSK.CHK', msg: 'Portfolio drawdown: -1.8% -- within limits' },
    { cmd: 'ORD.EXEC', msg: 'BTC/USDT -- BUY 0.5 @ $67,432 -- FILLED' },
    { cmd: 'MKT.SCAN', msg: 'Scanning full crypto universe (108 tickers)...' },
    { cmd: 'SIG.GEN', msg: 'ETH/USDT -- BUY signal -- confidence 0.76' },
    { cmd: 'SIG.GEN', msg: 'PEPE/USDT -- SELL signal -- confidence 0.69', cls: 'err' },
    { cmd: 'COR.CHK', msg: 'BTC/ETH correlation: 0.87 -- adjusting size' },
    { cmd: 'RSK.CHK', msg: 'Circuit breaker: nominal -- daily P&L +2.1%' },
    { cmd: 'SIG.GEN', msg: 'SOL/USDT -- BUY signal -- confidence 0.84' },
    { cmd: 'ORD.EXEC', msg: 'ETH/USDT -- BUY 2.0 @ $3,521 -- FILLED' },
    { cmd: 'SL.TP', msg: 'Monitoring 4 positions -- next check 30s' },
    { cmd: 'RGM.CALC', msg: 'Sector rotation: AI tokens gaining momentum', cls: 'warn' },
    { cmd: 'RSK.PAR', msg: 'Risk parity rebalance: 8 positions adjusted' },
    { cmd: 'AGT.LOOP', msg: 'Autonomous cycle complete -- next scan in 5m' },
    { cmd: 'SIG.GEN', msg: 'RNDR/USDT -- BUY signal -- confidence 0.73' },
    { cmd: 'GCR.RULE', msg: 'Contrarian filter: SHIB euphoria detected -- skip' },
    { cmd: 'WS.FEED', msg: 'Broadcasting 3 new signals to WebSocket clients' },
  ];

  const maxLines = 14;
  let idx = 0;

  function now() {
    const d = new Date();
    return [d.getHours(), d.getMinutes(), d.getSeconds()]
      .map(n => String(n).padStart(2, '0')).join(':');
  }

  function addLine() {
    const e = entries[idx % entries.length];
    const div = document.createElement('div');
    div.className = 'ops-demo-line';
    div.innerHTML =
      '<span class="ops-demo-ts">' + now() + '</span>' +
      '<span class="ops-demo-cmd">' + e.cmd + '</span>' +
      '<span class="ops-demo-msg' + (e.cls ? ' ' + e.cls : '') + '">' + e.msg + '</span>';
    log.appendChild(div);
    if (log.children.length > maxLines) log.removeChild(log.firstChild);
    idx++;
    setTimeout(addLine, 1800 + Math.random() * 2200);
  }

  for (let i = 0; i < 5; i++) {
    const e = entries[i];
    const div = document.createElement('div');
    div.className = 'ops-demo-line';
    div.innerHTML =
      '<span class="ops-demo-ts">' + now() + '</span>' +
      '<span class="ops-demo-cmd">' + e.cmd + '</span>' +
      '<span class="ops-demo-msg' + (e.cls ? ' ' + e.cls : '') + '">' + e.msg + '</span>';
    log.appendChild(div);
    idx++;
  }
  setTimeout(addLine, 2000);
});
